version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8080/api}
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./lego-api
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - MBL_SQL_HOST=${MBL_SQL_HOST}
      - MBL_SQL_USER=${MBL_SQL_USER}
      - MBL_SQL_PASS=${MBL_SQL_PASS}
      - MBL_SQL_PORT=${MBL_SQL_PORT:-3306}
      - MBL_CORS_ORIGIN=${MBL_CORS_ORIGIN}
    restart: unless-stopped