import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faFire, 
  faHouse,
  faFolderOpen,
  faFolderPlus,
  faHeart,
  faUser,
  faUserPlus,
  faRightFromBracket,
  faMagnifyingGlass,
  faShare,
  faShareAlt,
  faThumbsUp,
  faPlus,
  faChevronDown,
  faChevronUp,
  faChevronRight,
  faBars,
  faXmark,
  faCircleInfo,
  faCamera,
  faTimes,
  faEdit,
  faSave,
  faCopy,
  faCircleHalfStroke,
  faEnvelope,
  faArrowLeft,
  faArrowRight,
  faTh,
  faList,
  faSearch,
  faFilter,
  faCube,
  faCubes,
  faFolder,
  faPuzzlePiece,
  faCheck,
  faCheckCircle,
  faShoppingBasket,
  faInfoCircle,
  faMapMarkerAlt,
  faTrash,
  faStore,
  faDollarSign,
  faEyeSlash,
  faEye,
  faSortDown,
  faSortUp,
  faBoxOpen,
  faBox,
  faUserCircle,
  faGift,
  faPiggyBank,
  faUsers,
  faClock,
  faTableCells,
  faListUl
} from '@fortawesome/free-solid-svg-icons';

import {
  faGithub,
  faTwitter,
  faYoutube
} from '@fortawesome/free-brands-svg-icons';

// Add all icons in a single call
library.add(
  // Solid icons
  faFire,
  faHouse,
  faFolderOpen,
  faFolderPlus,
  faHeart,
  faUser,
  faUserPlus,
  faRightFromBracket,
  faMagnifyingGlass,
  faShare,
  faShareAlt,
  faThumbsUp,
  faPlus,
  faXmark,
  faChevronDown,
  faChevronUp,
  faChevronRight,
  faBars,
  faCircleInfo,
  faCamera,
  faTimes,
  faEdit,
  faSave,
  faCopy,
  faCircleHalfStroke,
  faEnvelope,
  faArrowLeft,
  faArrowRight,
  faTh,
  faList,
  faTableCells,  // Alternative for faTh
  faListUl,      // Alternative for faList
  faSearch,
  faFilter,
  faCube,
  faCubes,
  faFolder,
  faPuzzlePiece,
  faCheck,
  faCheckCircle,
  faShoppingBasket,
  faInfoCircle,
  faMapMarkerAlt,
  faTrash,
  faStore,
  faDollarSign,
  faEyeSlash,
  faEye,
  faSortDown,
  faSortUp,
  faBoxOpen,
  faBox,
  faUserCircle,
  faGift,
  faPiggyBank,
  faUsers,
  faClock,
  
  // Brand icons
  faGithub,
  faTwitter,
  faYoutube
);